env: "mode" # Режим работы сервера: local, dev, prod

server:
  server_port: ":port" # Порт сервера
  server_mode: "mode" # Режим сервера: release, debug
  read_timeout: "10s" # Таймаут чтения
  write_timeout: "10s" # Таймаут записи
  idle_timeout: "60s" # Таймаут бездействия
  shutdown_context_value: "5s" # Таймаут остановки при graceful shutdown

postgre:
  pool_max: 20 # Максимальное количество подключений в пуле
  retry_attempts: 5 # Количество попыток подключения
  retry_delay: "2s" # Задержка между попытками подключения
  context_timeout_value: "5s" # Таймаут контекста подключения
